# Generated by Django 3.2.23 on 2024-02-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='subjects',
            field=models.ManyToManyField(to='profils.Subject'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.duration'),
        ),
    ]
