# Generated by Django 3.2.24 on 2024-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
        ('jobs', '0002_auto_20240226_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='profils.Subject'),
        ),
    ]
