# Generated by Django 3.2.24 on 2024-03-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professor_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.professor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.student'),
        ),
    ]
